Add Swiss Re changes to support sts token-based authentication
aliyun/aliyun-odps-r-plugin pull request #18
Opened 2022-06-13 15:32 UTC by bodhipaolo

I added a small change to support Alibaba STS token based authentication in order to use Ram Roles with RODPS.
I also updated pom.xml to enforce odps-sdk-core upgrade from 0.32.5-public to 0.38.4-public.

I also updated buildall.sh script, but since it is not relevant for sts support, feel free to discard it in case.

Thank you.

Kind regards,
Paolo.

2022-06-13 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/aliyun-odps-r-plugin?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/aliyun-odps-r-plugin?pullRequest=18) before we can accept your contribution.<br/><hr/>**Paolo Tortora** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/aliyun-odps-r-plugin?pullRequest=18) it.</sub>

2022-06-14 14:25 UTC, lyman requested changes

2022-06-14 14:25 UTC, lyman commented on java/src/main/java/com/aliyun/odps/rodps/ROdps.java
> +  public ROdps(String projectName, String accessID, String accessKey, String stsToken, String endPoint,
This new constructor for ststoken is well implemented.
But I find nowhere this constructor is invoked. Maybe you forget add changes to RODPS/R/init.R in your commit?

2022-06-14 14:30 UTC, bodhipaolo commented on java/src/main/java/com/aliyun/odps/rodps/ROdps.java
> +  public ROdps(String projectName, String accessID, String accessKey, String stsToken, String endPoint,
Hi Lyman,

It had to be there actually, not sure where was not in the commit of pull request as we fully tested it.

Let me fix it.

2022-06-14 14:41 UTC, bodhipaolo commented on java/src/main/java/com/aliyun/odps/rodps/ROdps.java
> +  public ROdps(String projectName, String accessID, String accessKey, String stsToken, String endPoint,
Hi Lyman.

I just added the commit for init.R.

Thanks for notifying it

2022-06-15 15:45 UTC, merged